server:
  port: 11000
spring:
  application:
    name: unified-dispose-examples-a
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/dynamic
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
      seata: true
#        db1:
#          url: jdbc:gbase://127.0.0.1:5258/dynamic
#          username: root
#          password: root
#          driver-class-name: com.gbase.jdbc.Driver
#feign.hystrix.enabled=true
